
SET(APP_NAME Simulator)

ADD_EXECUTABLE(${APP_NAME})

TARGET_SOURCES(${APP_NAME}
  PUBLIC  ${PROJECT_SOURCE_DIR}/Simulator.hpp
)

IF (APPLE)
  TARGET_SOURCES(${APP_NAME}
    PRIVATE ${PROJECT_SOURCE_DIR}/Simulator.mm
  )
ENDIF()

INCLUDE(Common)

SET_TARGET_PROPERTIES(${APP_NAME} PROPERTIES
  VERSION  "${${PROJECT_NAME}_VERSION}"
  LINKER_LANGUAGE  "${PROJECT_LINKER}"
)

set_compiler_version(
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED ON
  CXX_EXTENSIONS ON

  OBJCXX_STANDARD 20
  OBJCXX_STANDARD_REQUIRED ON
  OBJCXX_EXTENSIONS ON
)

COMMON_SET_TARGET_PROPERTIES()

FIND_PACKAGE(imgui REQUIRED)
IF(imgui_FOUND)
  TARGET_LINK_LIBRARIES(${APP_NAME} PUBLIC imgui::imgui)
ENDIF()

FIND_PACKAGE(Processor REQUIRED)
IF(Processor_FOUND)
  TARGET_LINK_LIBRARIES(${APP_NAME} PUBLIC Processor::Processor)
  TARGET_COMPILE_OPTIONS(Processor PRIVATE "-ferror-limit=50")
  TARGET_COMPILE_DEFINITIONS(Processor PRIVATE ${PROJECT_COMPILE_DEFINITIONS})
ENDIF()

GET_TARGET_PROPERTY(imgui_prop "imgui" INTERFACE_COMPILE_DEFINITIONS)
TARGET_COMPILE_DEFINITIONS(${APP_NAME} PRIVATE "${imgui_prop}")

common_create_install(NAME "${APP_NAME}" TARGETS "${APP_NAME}")
