
SET(APP_NAME Simulator)

ADD_EXECUTABLE(${APP_NAME})

TARGET_SOURCES(${APP_NAME}
  PUBLIC  ${PROJECT_SOURCE_DIR}/Simulator.hpp
)

IF (APPLE)
  TARGET_SOURCES(${APP_NAME}
    PRIVATE ${PROJECT_SOURCE_DIR}/Simulator.mm
  )
ENDIF()

SOURCE_GROUP(${APP_NAME} FILES
  ${PROJECT_SOURCE_DIR}/Simulator.hpp
  ${PROJECT_SOURCE_DIR}/Simulator.mm
)

INCLUDE(Common)

SET_TARGET_PROPERTIES(${APP_NAME} PROPERTIES
  VERSION  "${${PROJECT_NAME}_VERSION}"
  LINKER_LANGUAGE  "${PROJECT_LINKER}"
)

set_compiler_version(
  CXX_STANDARD 20
  CXX_STANDARD_REQUIRED ON
  CXX_EXTENSIONS ON

  OBJCXX_STANDARD 20
  OBJCXX_STANDARD_REQUIRED ON
  OBJCXX_EXTENSIONS ON
)

COMMON_SET_TARGET_PROPERTIES()

FIND_PACKAGE(imgui REQUIRED)
IF(imgui_FOUND)
  MESSAGE(STATUS "FOUND IMGUI!")
  TARGET_LINK_LIBRARIES(${APP_NAME} PUBLIC imgui::imgui)
ENDIF()

FIND_PACKAGE(Processor REQUIRED)
IF(Processor_FOUND)
  TARGET_LINK_LIBRARIES(${APP_NAME} PUBLIC Processor::Processor)
  TARGET_COMPILE_OPTIONS(Processor PRIVATE "-ferror-limit=50")
  TARGET_COMPILE_DEFINITIONS(Processor PRIVATE ${PROJECT_COMPILE_DEFINITIONS})
ENDIF()

IF (TARGET imgui)
  GET_TARGET_PROPERTY(imgui_ILL "imgui" INTERFACE_LINK_LIBRARIES)
  GET_TARGET_PROPERTY(imgui_IID "imgui" INTERFACE_INCLUDE_DIRECTORIES)
  MESSAGE(STATUS "IMGUI ILL: ${imgui_ILL}")
  MESSAGE(STATUS "IMGUI IID: ${imgui_IID}")
ENDIF()

common_create_install(NAME "${APP_NAME}" TARGETS "${APP_NAME}")
