# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/txc/Projects/CPP/CMake/Common.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/txc/Projects/CPP/UserInterfaces/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/txc/Projects/CPP/UserInterfaces/Demo/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/txc/Projects/CPP/UserInterfaces/ImGuiDemo/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/txc/Projects/CPP/UserInterfaces/Simulator/CMakeLists.txt))

/Users/txc/Projects/CPP/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/txc/Projects/CPP -B/Users/txc/Projects/CPP/xcode
