add_test( [==[Initialization Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Initialization Tests]==]  )
set_tests_properties( [==[Initialization Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[ADC - Add with Carry Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[ADC - Add with Carry Tests]==]  )
set_tests_properties( [==[ADC - Add with Carry Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[AND - Compare Memory with Accumulator]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[AND - Compare Memory with Accumulator]==]  )
set_tests_properties( [==[AND - Compare Memory with Accumulator]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[ASL - Arithmetic Shift Left]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[ASL - Arithmetic Shift Left]==]  )
set_tests_properties( [==[ASL - Arithmetic Shift Left]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BCC - Branch On Carry Clear]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BCC - Branch On Carry Clear]==]  )
set_tests_properties( [==[BCC - Branch On Carry Clear]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BCS - Branch on Carry Set]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BCS - Branch on Carry Set]==]  )
set_tests_properties( [==[BCS - Branch on Carry Set]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BEQ - Branch on Zero Set]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BEQ - Branch on Zero Set]==]  )
set_tests_properties( [==[BEQ - Branch on Zero Set]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BIT - Compare Memory with Accumulator]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BIT - Compare Memory with Accumulator]==]  )
set_tests_properties( [==[BIT - Compare Memory with Accumulator]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BMI - Branch if Negative Set]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BMI - Branch if Negative Set]==]  )
set_tests_properties( [==[BMI - Branch if Negative Set]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BNE - Branch On Result Not Zero]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BNE - Branch On Result Not Zero]==]  )
set_tests_properties( [==[BNE - Branch On Result Not Zero]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BPL - Branch if Negative Clear]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BPL - Branch if Negative Clear]==]  )
set_tests_properties( [==[BPL - Branch if Negative Clear]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BRK - Simulate Interrupt Request (IRQ)]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BRK - Simulate Interrupt Request (IRQ)]==]  )
set_tests_properties( [==[BRK - Simulate Interrupt Request (IRQ)]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BVC - Branch if Overflow Clear]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BVC - Branch if Overflow Clear]==]  )
set_tests_properties( [==[BVC - Branch if Overflow Clear]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[BVS - Branch if Overflow Set]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[BVS - Branch if Overflow Set]==]  )
set_tests_properties( [==[BVS - Branch if Overflow Set]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CLC - Clear Carry Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CLC - Clear Carry Flag]==]  )
set_tests_properties( [==[CLC - Clear Carry Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CLD - Clear Decimal Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CLD - Clear Decimal Flag]==]  )
set_tests_properties( [==[CLD - Clear Decimal Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CLI - Clear Interrupt Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CLI - Clear Interrupt Flag]==]  )
set_tests_properties( [==[CLI - Clear Interrupt Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CLV - Clear Overflow Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CLV - Clear Overflow Flag]==]  )
set_tests_properties( [==[CLV - Clear Overflow Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CMP - Compare Memory With Accumulator]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CMP - Compare Memory With Accumulator]==]  )
set_tests_properties( [==[CMP - Compare Memory With Accumulator]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CPX - Compare Memory With X Register]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CPX - Compare Memory With X Register]==]  )
set_tests_properties( [==[CPX - Compare Memory With X Register]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[CPY - Compare Memory With X Register]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[CPY - Compare Memory With X Register]==]  )
set_tests_properties( [==[CPY - Compare Memory With X Register]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[DEC - Decrement Memory by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[DEC - Decrement Memory by One]==]  )
set_tests_properties( [==[DEC - Decrement Memory by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[DEX - Decrement X by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[DEX - Decrement X by One]==]  )
set_tests_properties( [==[DEX - Decrement X by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[DEY - Decrement Y by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[DEY - Decrement Y by One]==]  )
set_tests_properties( [==[DEY - Decrement Y by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[EOR - Exclusive OR Compare Accumulator With Memory]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[EOR - Exclusive OR Compare Accumulator With Memory]==]  )
set_tests_properties( [==[EOR - Exclusive OR Compare Accumulator With Memory]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[INC - Increment Memory by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[INC - Increment Memory by One]==]  )
set_tests_properties( [==[INC - Increment Memory by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[INX - Increment X by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[INX - Increment X by One]==]  )
set_tests_properties( [==[INX - Increment X by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[INY - Increment Y by One]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[INY - Increment Y by One]==]  )
set_tests_properties( [==[INY - Increment Y by One]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[JMP - Jump to New Location]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[JMP - Jump to New Location]==]  )
set_tests_properties( [==[JMP - Jump to New Location]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[JSR - Jump to SubRoutine]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[JSR - Jump to SubRoutine]==]  )
set_tests_properties( [==[JSR - Jump to SubRoutine]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[LDA - Load Accumulator with Memory]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[LDA - Load Accumulator with Memory]==]  )
set_tests_properties( [==[LDA - Load Accumulator with Memory]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[LDX - Load X with Memory]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[LDX - Load X with Memory]==]  )
set_tests_properties( [==[LDX - Load X with Memory]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[LDY - Load Y with Memory]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[LDY - Load Y with Memory]==]  )
set_tests_properties( [==[LDY - Load Y with Memory]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[LSR - Logical Shift Right]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[LSR - Logical Shift Right]==]  )
set_tests_properties( [==[LSR - Logical Shift Right]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[ORA - Bitwise OR Compare Memory with Accumulator]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[ORA - Bitwise OR Compare Memory with Accumulator]==]  )
set_tests_properties( [==[ORA - Bitwise OR Compare Memory with Accumulator]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[PHA - Push Accumulator Onto Stack]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[PHA - Push Accumulator Onto Stack]==]  )
set_tests_properties( [==[PHA - Push Accumulator Onto Stack]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[PHP - Push Flags Onto Stack]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[PHP - Push Flags Onto Stack]==]  )
set_tests_properties( [==[PHP - Push Flags Onto Stack]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[PLA - Pull From Stack to Accumulator]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[PLA - Pull From Stack to Accumulator]==]  )
set_tests_properties( [==[PLA - Pull From Stack to Accumulator]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[PLP - Pull From Stack to Flags]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[PLP - Pull From Stack to Flags]==]  )
set_tests_properties( [==[PLP - Pull From Stack to Flags]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[ROL - Rotate Left]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[ROL - Rotate Left]==]  )
set_tests_properties( [==[ROL - Rotate Left]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[ROR - Rotate Right]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[ROR - Rotate Right]==]  )
set_tests_properties( [==[ROR - Rotate Right]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[RTI - Return from Interrupt]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[RTI - Return from Interrupt]==]  )
set_tests_properties( [==[RTI - Return from Interrupt]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[RTS - Return from SubRoutine]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[RTS - Return from SubRoutine]==]  )
set_tests_properties( [==[RTS - Return from SubRoutine]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[SBC - Subtraction With Borrow]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[SBC - Subtraction With Borrow]==]  )
set_tests_properties( [==[SBC - Subtraction With Borrow]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[SEC - Set Carry Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[SEC - Set Carry Flag]==]  )
set_tests_properties( [==[SEC - Set Carry Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Set Decimal Mode]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Set Decimal Mode]==]  )
set_tests_properties( [==[Set Decimal Mode]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[SEI - Set Interrupt Flag]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[SEI - Set Interrupt Flag]==]  )
set_tests_properties( [==[SEI - Set Interrupt Flag]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[STA - Store Accumulator In Memory]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[STA - Store Accumulator In Memory]==]  )
set_tests_properties( [==[STA - Store Accumulator In Memory]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[STX - Set Memory To X]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[STX - Set Memory To X]==]  )
set_tests_properties( [==[STX - Set Memory To X]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[STY - Set Memory To Y]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[STY - Set Memory To Y]==]  )
set_tests_properties( [==[STY - Set Memory To Y]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[TAX, TAY, TSX, TSY Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[TAX\, TAY\, TSX\, TSY Tests]==]  )
set_tests_properties( [==[TAX, TAY, TSX, TSY Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[TSX - Transfer Stack Pointer to X Register]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[TSX - Transfer Stack Pointer to X Register]==]  )
set_tests_properties( [==[TSX - Transfer Stack Pointer to X Register]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[TXS - Transfer X Register to Stack Pointer]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[TXS - Transfer X Register to Stack Pointer]==]  )
set_tests_properties( [==[TXS - Transfer X Register to Stack Pointer]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Accumulator Address Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Accumulator Address Tests]==]  )
set_tests_properties( [==[Accumulator Address Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Index Address Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Index Address Tests]==]  )
set_tests_properties( [==[Index Address Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Compare Address Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Compare Address Tests]==]  )
set_tests_properties( [==[Compare Address Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Decrement/Increment Address Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Decrement/Increment Address Tests]==]  )
set_tests_properties( [==[Decrement/Increment Address Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Store In Memory Address Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Store In Memory Address Tests]==]  )
set_tests_properties( [==[Store In Memory Address Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Cycle Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Cycle Tests]==]  )
set_tests_properties( [==[Cycle Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
add_test( [==[Program Counter Tests]==] /Users/txc/Projects/CPP/xcode/ProcessorTests/Debug/ProcessorTests [==[Program Counter Tests]==]  )
set_tests_properties( [==[Program Counter Tests]==] PROPERTIES WORKING_DIRECTORY /Users/txc/Projects/CPP/xcode/ProcessorTests)
set( ProcessorTests_TESTS [==[Initialization Tests]==] [==[ADC - Add with Carry Tests]==] [==[AND - Compare Memory with Accumulator]==] [==[ASL - Arithmetic Shift Left]==] [==[BCC - Branch On Carry Clear]==] [==[BCS - Branch on Carry Set]==] [==[BEQ - Branch on Zero Set]==] [==[BIT - Compare Memory with Accumulator]==] [==[BMI - Branch if Negative Set]==] [==[BNE - Branch On Result Not Zero]==] [==[BPL - Branch if Negative Clear]==] [==[BRK - Simulate Interrupt Request (IRQ)]==] [==[BVC - Branch if Overflow Clear]==] [==[BVS - Branch if Overflow Set]==] [==[CLC - Clear Carry Flag]==] [==[CLD - Clear Decimal Flag]==] [==[CLI - Clear Interrupt Flag]==] [==[CLV - Clear Overflow Flag]==] [==[CMP - Compare Memory With Accumulator]==] [==[CPX - Compare Memory With X Register]==] [==[CPY - Compare Memory With X Register]==] [==[DEC - Decrement Memory by One]==] [==[DEX - Decrement X by One]==] [==[DEY - Decrement Y by One]==] [==[EOR - Exclusive OR Compare Accumulator With Memory]==] [==[INC - Increment Memory by One]==] [==[INX - Increment X by One]==] [==[INY - Increment Y by One]==] [==[JMP - Jump to New Location]==] [==[JSR - Jump to SubRoutine]==] [==[LDA - Load Accumulator with Memory]==] [==[LDX - Load X with Memory]==] [==[LDY - Load Y with Memory]==] [==[LSR - Logical Shift Right]==] [==[ORA - Bitwise OR Compare Memory with Accumulator]==] [==[PHA - Push Accumulator Onto Stack]==] [==[PHP - Push Flags Onto Stack]==] [==[PLA - Pull From Stack to Accumulator]==] [==[PLP - Pull From Stack to Flags]==] [==[ROL - Rotate Left]==] [==[ROR - Rotate Right]==] [==[RTI - Return from Interrupt]==] [==[RTS - Return from SubRoutine]==] [==[SBC - Subtraction With Borrow]==] [==[SEC - Set Carry Flag]==] [==[Set Decimal Mode]==] [==[SEI - Set Interrupt Flag]==] [==[STA - Store Accumulator In Memory]==] [==[STX - Set Memory To X]==] [==[STY - Set Memory To Y]==] [==[TAX, TAY, TSX, TSY Tests]==] [==[TSX - Transfer Stack Pointer to X Register]==] [==[TXS - Transfer X Register to Stack Pointer]==] [==[Accumulator Address Tests]==] [==[Index Address Tests]==] [==[Compare Address Tests]==] [==[Decrement/Increment Address Tests]==] [==[Store In Memory Address Tests]==] [==[Cycle Tests]==] [==[Program Counter Tests]==])
