# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Processor::Processor)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Processor::Processor
add_library(Processor::Processor STATIC IMPORTED)

set_target_properties(Processor::Processor PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_20"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/txc/Projects/CPP/Processor;/Users/txc/Projects/CPP/Processor"
  INTERFACE_LINK_LIBRARIES "fmt::fmt-header-only;spdlog::spdlog_header_only"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(Processor::Processor
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS "/Users/txc/Projects/CPP/Processor" "/Users/txc/Projects/CPP/Processor" "/Users/txc/Projects/CPP/Processor" "/Users/txc/Projects/CPP/Processor"
      FILES "/Users/txc/Projects/CPP/Processor/Bus.hpp" "/Users/txc/Projects/CPP/Processor/Exceptions.hpp" "/Users/txc/Projects/CPP/Processor/Executioner.hpp" "/Users/txc/Projects/CPP/Processor/Formatters.hpp" "/Users/txc/Projects/CPP/Processor/Logger.hpp" "/Users/txc/Projects/CPP/Processor/Processor.hpp" "/Users/txc/Projects/CPP/Processor/Singleton.hpp" "/Users/txc/Projects/CPP/Processor/Types.hpp"
  )
endif()

# Import target "Processor::Processor" for configuration "Debug"
set_property(TARGET Processor::Processor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Processor::Processor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/txc/Projects/CPP/xcode/Processor/Debug/libProcessor.a"
  )

# Import target "Processor::Processor" for configuration "Release"
set_property(TARGET Processor::Processor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Processor::Processor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/txc/Projects/CPP/xcode/Processor/Release/libProcessor.a"
  )

# Import target "Processor::Processor" for configuration "MinSizeRel"
set_property(TARGET Processor::Processor APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Processor::Processor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/txc/Projects/CPP/xcode/Processor/MinSizeRel/libProcessor.a"
  )

# Import target "Processor::Processor" for configuration "RelWithDebInfo"
set_property(TARGET Processor::Processor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Processor::Processor PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/txc/Projects/CPP/xcode/Processor/RelWithDebInfo/libProcessor.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
