SET(APP imgui)

SET( ${APP}_HEADER_SEARCH_DIRS
  "${CMAKE_SOURCE_DIR}/"
  "${CMAKE_SOURCE_DIR}/includes"
)
SET(${APP}_LIB)

# Check environment for root search directory
SET(${APP}_ENV_ROOT $ENV{${APP}_ROOT})
  IF(NOT ${APP}_ROOT AND ${APP}_ENV_ROOT)
  SET(${APP}_ROOT ${${APP}_ENV_ROOT})
ENDIF()
UNSET(${APP}_ENV_ROOT)

IF(${APP}_ROOT)
  LIST(INSERT ${APP}_HEADER_SEARCH_DIRS 0 "${${APP}_ROOT}/")
ENDIF()

# Search for the header
FIND_PATH(${APP}_INCLUDE_DIR "imgui.h"
  PATHS ${${APP}_HEADER_SEARCH_DIRS}
  PATH_SUFFIXES "imgui"
)
UNSET(${APP}_HEADER_SEARCH_DIRS)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(${APP} DEFAULT_MSG ${APP}_INCLUDE_DIR)
MARK_AS_ADVANCED(${APP}_INCLUDE_DIR ${APP}_LIB)
