SET(APP Processor)

SET( ${APP}_HEADER_SEARCH_DIRS
  "${CMAKE_SOURCE_DIR}/"
  "${CMAKE_SOURCE_DIR}/includes"
)
SET(${APP}_LIB)

# Check environment for root search directory
SET(${APP}_ENV_ROOT $ENV{${APP}_ROOT})
  IF(NOT ${APP}_ROOT AND ${APP}_ENV_ROOT)
  SET(${APP}_ROOT ${${APP}_ENV_ROOT})
ENDIF()
UNSET(${APP}_ENV_ROOT)

IF(${APP}_ROOT)
  LIST(INSERT ${APP}_HEADER_SEARCH_DIRS 0 "${${APP}_ROOT}/")
ENDIF()

# Search for the header
FIND_PATH(${APP}_INCLUDE_DIR "Processor.hpp"
  PATHS ${${APP}_HEADER_SEARCH_DIRS}
  PATH_SUFFIXES "Processor"
)
UNSET(${APP}_HEADER_SEARCH_DIRS)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(${APP} DEFAULT_MSG ${APP}_INCLUDE_DIR)
MARK_AS_ADVANCED(${APP}_INCLUDE_DIR ${APP}_LIB)

#[===[
IF(${APP}_FOUND)
  FIND_PACKAGE(fmt REQUIRED CONFIG)
  IF(fmt_FOUND)
    LIST(APPEND ${APP}_LIB fmt::fmt-header-only)
  ENDIF()

  FIND_PACKAGE(spdlog REQUIRED)
  IF(spdlog_FOUND)
    LIST(APPEND ${APP}_LIB spdlog::spdlog_header_only)
  ENDIF()

  IF(NOT TARGET ${APP})
    ADD_LIBRARY(${APP} SHARED IMPORTED)
    ADD_LIBRARY(${APP_NAME}::${APP_NAME} ALIAS ${APP_NAME})

    SET_TARGET_PROPERTIES(${APP}
      PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
      IMPORTED_LOCATION "${${APP}_INCLUDE_DIR}"
      INTERFACE_INCLUDE_DIRECTORIES "${${APP}_INCLUDE_DIR}"
      INTERFACE_LINK_LIBRARIES "${${APP}_LIB}"
      INTERFACE_COMPILE_DEFINITIONS "DECIMAL_MODE=1"
    )
  ENDIF()
  IF(NOT TARGET ${APP})
    ADD_LIBRARY(${APP}-no-decimalmode SHARED IMPORTED)
    ADD_LIBRARY(${APP_NAME}::${APP_NAME}-no-decimalmode ALIAS ${APP_NAME})
    
    SET_TARGET_PROPERTIES(${APP}-no-decimalmode
      PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
      IMPORTED_LOCATION "${${APP}_INCLUDE_DIR}"
      INTERFACE_INCLUDE_DIRECTORIES "${${APP}_INCLUDE_DIR}"
      INTERFACE_LINK_LIBRARIES "${${APP}_LIB}"
      INTERFACE_COMPILE_DEFINITIONS "DECIMAL_MODE=0"
    )
  ENDIF()
  IF(NOT TARGET ${APP}-header-only)
    ADD_LIBRARY(${APP}-header-only INTERFACE IMPORTED)
    ADD_LIBRARY(${APP_NAME}::${APP_NAME}-header-only ALIAS ${APP_NAME}-header-only)
    SET_TARGET_PROPERTIES(${APP}-header-only
      PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES "CXX"
      IMPORTED_LOCATION "${${APP}_INCLUDE_DIR}"
      INTERFACE_INCLUDE_DIRECTORIES "${${APP}_INCLUDE_DIR}"
      INTERFACE_LINK_LIBRARIES "${${APP}_LIB}"
    )
  ENDIF()
ENDIF()
]===]
